const data = {
    countryList: [
        ["US", "美國"],
        ["SE", "瑞典"],
        ["CN", "中國"],
        ["FR", "法國"],
        ["TW", "台灣"],
        ["JP", "日本"],
        ["KR", "南韓"],
        ["AU", "澳洲"],
        ["CA", "加拿大"],
        ["IT", "義大利"],
        ["DE", "德國"],
    ],
    currencyList: [
        ["USD", "美金"],
        ["NTD", "台幣"],
        ["RMB", "人民幣"],
        ["HKD", "港幣"],
        ["EUR", "歐元"],
        ["JPY", "日幣"],
    ],
    exchangeRate: [
        ["USD", "USD", "1"],
        ["NTD", "USD", "29.4"],
        ["RMB", "USD", "6.59"],
        ["HKD", "USD", "7.85"],
        ["EUR", "USD", "0.95"],
        ["JPY", "USD", "130.33"],
    ],
    inquiryQty: [10, 250, 1000, 5000],
    listCollections: {
        all: ["更新", "刪除"],
        customers2: [
            "客戶",
            ["客戶編號", "公司名稱", "聯繫", "地區"],
            ["id", "company", "contacts", "country"],
        ],
        suppliers2: [
            "廠商",
            ["廠商編號", "公司名稱", "聯繫", "地區"],
            ["id", "company", "contacts", "country"],
        ],
        products2: [
            "產品",
            [
                "產品編號",
                "類別",
                "系列",
                "材質",
                "色碼",
                "款式",
                "特殊",
                "備註",
            ],
            [
                "id",
                "class",
                "group",
                "material",
                "color",
                "type",
                "special",
                "mark",
            ],
        ],
        parts2: [
            "零件",
            ["零件編號", "型號", "項目", "系列", "規格1", "規格2", "規格3"],
            ["id", "mark", "class", "group", "spec1", "spec2", "spec3"],
        ],
        bom: [
            "結構",
            ["產品編號", "零件編號", "SN", "用量", "單位"],
            ["id0", "id1", "id2", "qty", "unit"],
        ],
        partQuotations2: [
            "零件報價",
            [
                "零件編號",
                "供應商編號",
                "數量",
                "單價",
                "幣別",
                "交期",
                "報價日期",
                "報價效期",
            ],
            [
                "id0",
                "id1",
                "inquiryQty",
                "price",
                "currency",
                "leadTime",
                "date",
                "valid",
            ],
        ],
        productQuotations2: [
            "產品報價",
            [
                "產品編號",
                "客戶編號",
                "數量",
                "單價",
                "幣別",
                "交期",
                "報價日期",
                "報價效期",
            ],
            [
                "id0",
                "id1",
                "inquiryQty",
                "price",
                "currency",
                "leadTime",
                "date",
                "valid",
            ],
        ],
        order: [
            "客戶訂單",
            [
                "客戶編號",
                "產品編號",
                "訂單編號",
                "訂單總金額",
                "幣別",
                "產品數量",
                "產品單價",
                "訂單日期",
                "需求交期",
                "備註",
            ],
            [
                "id0",
                "id1",
                "orderId",
                "sum",
                "currency",
                "qty",
                "price",
                "date",
                "requestedDate",
                "remark",
            ],
        ],
    },
    listWithCheckBoxCollections: {
        all: ["選取"],
        customers2: [
            "客戶",
            ["客戶編號", "公司名稱", "聯繫人", "地區"],
            ["id", "company", "contacts", "country"],
        ],
        suppliers2: [
            "廠商",
            ["廠商編號", "公司名稱", "聯繫人", "地區"],
            ["id", "company", "contacts", "country"],
        ],
        products2: [
            "產品",
            [
                "產品編號",
                "類別",
                "系列",
                "材質",
                "色碼",
                "款式",
                "特殊",
                "備註",
            ],
            [
                "id",
                "class",
                "group",
                "material",
                "color",
                "type",
                "special",
                "mark",
            ],
        ],
        parts2: [
            "零件",
            ["零件編號", "型號", "項目", "系列", "規格1", "規格2", "規格3"],
            ["id", "mark", "class", "group", "spec1", "spec2", "spec3"],
        ],
        partQuotations2: [
            "零件報價",
            [
                "零件廠商編號",
                "報價日期",
                "有效日期",
                "幣別",
                "數量",
                "單價",
                "交期",
            ],
            [
                "id",
                "date",
                "valid",
                "currency",
                "inquiryQty",
                "price",
                "leadTime",
            ],
        ],
        bom: [
            "產品結構",
            [
                "產品編號",
                "類別",
                "系列",
                "材質",
                "色碼",
                "款式",
                "特殊",
                "備註",
            ],
            ["id", "class", "group", "material", "color", "type", "special"],
        ],
    },
    assembleDataCollections: {
        bom: [
            "結構",
            ["產品編號", "系列", "材質", "色碼", "款式"],
            ["id", "group", "material", "color", "type"],
            ["零件編號", "型號"],
            ["id", "mark"],
            ["使用量", "單位", "順序", "刪除"],
            ["qty", "unit", "index"],
        ],
        partQuotations2: [
            "零件報價",
            ["報價日期", "有效日期", "幣別", "廠商編號", "公司名稱"],
            ["date", "valid", "currency", "id", "company"],
            ["零件編號", "型號"],
            ["id", "mark"],
            ["數量", "單價", "交期", "刪除"],
            ["inquiryQty", "price", "leadTime"],
        ],
        productQuotations2: [
            "產品報價",
            ["報價日期", "有效日期", "幣別", "客戶編號", "公司名稱"],
            ["date", "valid", "currency", "id", "company"],
            ["產品編號", "系列"],
            ["id", "group"],
            ["數量", "單價", "交期", "刪除"],
            ["inquiryQty", "price", "leadTime"],
        ],
        order: [
            "訂單",
            [
                "訂單編號",
                "訂單日期",
                "需求交期",
                "訂單總金額",
                "幣別",
                "客戶編號",
                "公司名稱",
            ],
            [
                "orderId",
                "date",
                "requestedDate",
                "sum",
                "currency",
                "id",
                "company",
            ],
            ["產品編號", "系列"],
            ["id", "group"],
            ["數量", "單價", "備註", "刪除"],
            ["qty", "price", "remark"],
        ],
        analysis: [
            "分析資料",
            [
                "分析日期",
                "分析有效日期",
                "產品編號",
                "系列",
                "分析數量",
                "總成本",
                "幣別",
            ],
            ["date", "valid", "id", "group", "quoteQty", "sum", "currency"],
            ["期望單價", "對應利潤率(%)"],
            ["expectedPrice", "caculatedMargin"],
            ["對應單價", "期望利潤率(%)"],
            ["caculatedPrice", "expoectedMargin"],
            [
                "零件編號",
                "使用量",
                "單位",
                "零件報價數量",
                "單價",
                "幣別",
                "交期",
                "報價有效日期",
                "廠商編號",
            ],
            [
                "idP",
                "qty",
                "unit",
                "inquiryQty",
                "price",
                "currency",
                "leadTime",
                "valid",
                "idF",
            ],
        ],
    },
    errorMessage: {
        bom: [
            "請選擇一個產品",
            "請選擇產品對應零件",
            "使用量需要填寫數字,非數字字元：",
            "順序需要為數字且唯一",
        ],
        partQuotations2: [
            "請選擇報價廠商",
            "請選擇需報價零件",
            "數量需要填寫數字,非數字字元：",
            "單價不能小於或為0",
            "請選擇幣別",
            "請選擇日期",
        ],
        productQuotations2: [
            "請選擇客戶資料",
            "請選擇需報價產品",
            "數量需要填寫數字,非數字字元：",
            "單價不能小於或為0",
            "請選擇幣別",
            "請選擇日期",
        ],
        order: [
            "請選擇客戶資料",
            "請選擇下單產品",
            "數量需要填寫數字,非數字字元：",
            "單價不能小於或為0",
            "請選擇幣別",
            "請選擇日期",
        ],
    },
    companies: {
        inputComponentArray: [
            {
                title: "公司名稱",
                name: "company",
            },
            {
                title: "聯繫資料",
                name: "contacts",
            },
        ],
    },
    part: {
        selectComponentArray: [
            {
                title: "項目",
                name: "class",
                optionArray: [["A", "半成品"]],
            },
            {
                title: "系列",
                name: "group",
                optionArray: [
                    ["A", "電器"],
                    ["B", "零件"],
                    ["C", "原料"],
                ],
            },
        ],
        A: [
            {
                title: "色溫",
                name: "spec1",
                optionArray: [
                    ["27", "2700K"],
                    ["30", "3000K"],
                    ["40", "4000K"],
                ],
            },
            {
                title: "瓦數",
                name: "spec2",
                optionArray: [
                    ["06", "6W"],
                    ["08", "8W"],
                    ["10", "10W"],
                ],
            },
            {
                title: "CRI",
                name: "spec3",
                optionArray: [
                    ["90", "90"],
                    ["95", "95"],
                    ["80", "80"],
                ],
            },
        ],
        B: [
            {
                title: "材質",
                name: "spec1",
                optionArray: [
                    ["BR", "黃銅"],
                    ["CO", "紅銅"],
                    ["ST", "鋼"],
                    ["AL", "鋁"],
                    ["SL", "不鏽鋼"],
                    ["AB", "ABS塑膠"],
                    ["PP", "PP塑膠"],
                    ["PC", "PC塑膠"],
                    ["PA", "PA塑膠"],
                ],
            },
            {
                title: "工藝",
                name: "spec2",
                optionArray: [
                    ["IJ", "注塑"],
                    ["DC", "壓鑄"],
                    ["FG", "鍛造"],
                    ["BD", "折彎"],
                    ["ET", "擠型"],
                    ["WE", "焊接"],
                    ["AS", "組裝"],
                    ["NN", "其他"],
                ],
            },
            {
                title: "表面",
                name: "spec3",
                optionArray: [
                    ["PA", "液烤"],
                    ["PC", "粉烤"],
                    ["PO", "拋光"],
                    ["PL", "電鍍"],
                    ["SB", "噴砂"],
                    ["BO", "染黑"],
                    ["NN", "去毛刺"],
                ],
            },
        ],
        C: [
            {
                title: "材質",
                name: "spec1",
                optionArray: [
                    ["Br", "黃銅"],
                    ["Co", "紅銅"],
                    ["ST", "鋼"],
                    ["AL", "鋁"],
                    ["SL", "不鏽鋼"],
                    ["PL", "塑膠"],
                ],
            },
            {
                title: "規格",
                name: "spec2",
                optionArray: [
                    ["00", "原料"],
                    ["01", "板材"],
                    ["02", "管材"],
                    ["10", "塑膠本色"],
                    ["11", "塑膠黑色"],
                    ["12", "塑膠色母"],
                    ["13", "塑膠色粉"],
                ],
            },
            {
                title: "顏色",
                name: "spec3",
                optionArray: [
                    ["00", "原料"],
                    ["01", "灰色"],
                    ["02", "紅色"],
                    ["03", "白色"],
                ],
            },
        ],
    },
    order: {
        inputComponentArray: [
            {
                title: "訂單編號",
                type: "text",
                name: "orderId",
            },
            {
                title: "訂單日期",
                type: "date",
                name: "date",
            },
            {
                title: "需求交期",
                type: "date",
                name: "requestedDate",
            },
        ],
    },
    product: {
        selectComponentArray: [
            {
                title: "類別",
                name: "class",
                optionArray: [
                    ["A", "燈具"],
                    ["B", "貿易"],
                ],
            },
            {
                title: "系列",
                name: "group",
                optionArray: [
                    ["A", "w102"],
                    ["B", "w127"],
                    ["C", "HOBO"],
                    ["D", "w153"],
                ],
            },
            {
                title: "材質",
                name: "material",
                optionArray: [
                    ["C", "黃銅"],
                    ["I", "鐵"],
                    ["P", "塑膠"],
                    ["S", "不鏽鋼"],
                ],
            },
            {
                title: "色碼",
                name: "color",
                optionArray: [
                    ["NNNN", "材質本色"],
                    ["9005", "RAL黑色"],
                    ["9016", "RAL白色"],
                    ["0580", "NSC紅色"],
                    ["0515", "NSC天藍色"],
                    ["1020", "NSC黃色"],
                    ["5010", "NSC褐色"],
                    ["6530", "NSC藍綠色"],
                ],
            },
            {
                title: "款式",
                name: "type",
                optionArray: [
                    ["T", "桌燈"],
                    ["S", "吊燈"],
                    ["W", "壁燈"],
                    ["F", "落地燈"],
                    ["W", "掛燈"],
                ],
            },
            {
                title: "特殊",
                name: "special",
                optionArray: [
                    ["NN", "無"],
                    ["02", "雙臂"],
                    ["01", "單臂"],
                    ["BN", "燈泡"],
                    ["NC", "304開關"],
                    ["ND", "調光開關"],
                    ["BC", "燈泡+304開關"],
                    ["BD", "燈泡+調光開關"],
                ],
            },
        ],
    },
    mapData: [
        ["gl", 10],
        ["sh", 11],
        ["bu", 12],
        ["lk", 13],
        ["as", 14],
        ["dk", 15],
        ["fo", 16],
        ["gu", 17],
        ["mp", 18],
        ["um", 19],
        ["us", 20],
        ["vi", 21],
        ["ca", 22],
        ["st", 23],
        ["jp", 24],
        ["cv", 25],
        ["dm", 26],
        ["sc", 27],
        ["nz", 28],
        ["ye", 29],
        ["jm", 30],
        ["ws", 31],
        ["om", 32],
        ["in", 33],
        ["vc", 34],
        ["bd", 35],
        ["sb", 36],
        ["lc", 37],
        ["fr", 38],
        ["nr", 39],
        ["no", 40],
        ["fm", 41],
        ["kn", 42],
        ["cn", 43],
        ["bh", 44],
        ["to", 45],
        ["fi", 46],
        ["id", 47],
        ["mu", 48],
        ["se", 49],
        ["tt", 50],
        ["sw", 51],
        ["br", 52],
        ["bs", 53],
        ["pw", 54],
        ["ec", 55],
        ["au", 56],
        ["tv", 57],
        ["mh", 58],
        ["cl", 59],
        ["ki", 60],
        ["ph", 61],
        ["gd", 62],
        ["ee", 63],
        ["ag", 64],
        ["es", 65],
        ["bb", 66],
        ["it", 67],
        ["mt", 68],
        ["mv", 69],
        ["sp", 70],
        ["pg", 71],
        ["vu", 72],
        ["sg", 73],
        ["gb", 74],
        ["cy", 75],
        ["gr", 76],
        ["km", 77],
        ["fj", 78],
        ["ru", 79],
        ["va", 80],
        ["sm", 81],
        ["am", 82],
        ["az", 83],
        ["ls", 84],
        ["tj", 85],
        ["ml", 86],
        ["dz", 87],
        ["tw", 88],
        ["uz", 89],
        ["tz", 90],
        ["ar", 91],
        ["sa", 92],
        ["nl", 93],
        ["ae", 94],
        ["ch", 95],
        ["pt", 96],
        ["my", 97],
        ["pa", 98],
        ["tr", 99],
        ["ir", 100],
        ["ht", 101],
        ["do", 102],
        ["gw", 103],
        ["hr", 104],
        ["th", 105],
        ["mx", 106],
        ["kw", 107],
        ["de", 108],
        ["gq", 109],
        ["cnm", 110],
        ["nc", 111],
        ["ie", 112],
        ["kz", 113],
        ["ge", 114],
        ["pl", 115],
        ["lt", 116],
        ["ug", 117],
        ["cd", 118],
        ["mk", 119],
        ["al", 120],
        ["ng", 121],
        ["cm", 122],
        ["bj", 123],
        ["tl", 124],
        ["tm", 125],
        ["kh", 126],
        ["pe", 127],
        ["mw", 128],
        ["mn", 129],
        ["ao", 130],
        ["mz", 131],
        ["za", 132],
        ["cr", 133],
        ["sv", 134],
        ["bz", 135],
        ["co", 136],
        ["kp", 137],
        ["kr", 138],
        ["gy", 139],
        ["hn", 140],
        ["ga", 141],
        ["ni", 142],
        ["et", 143],
        ["sd", 144],
        ["so", 145],
        ["gh", 146],
        ["ci", 147],
        ["si", 148],
        ["gt", 149],
        ["ba", 150],
        ["jo", 151],
        ["sy", 152],
        ["we", 153],
        ["il", 154],
        ["eg", 155],
        ["zm", 156],
        ["mc", 157],
        ["uy", 158],
        ["rw", 159],
        ["bo", 160],
        ["cg", 161],
        ["eh", 162],
        ["rs", 163],
        ["me", 164],
        ["tg", 165],
        ["mm", 166],
        ["la", 167],
        ["af", 168],
        ["jk", 169],
        ["pk", 170],
        ["bg", 171],
        ["ua", 172],
        ["ro", 173],
        ["qa", 174],
        ["li", 175],
        ["at", 176],
        ["sk", 177],
        ["sz", 178],
        ["hu", 179],
        ["ly", 180],
        ["ne", 181],
        ["lu", 182],
        ["ad", 183],
        ["lr", 184],
        ["sl", 185],
        ["bn", 186],
        ["mr", 187],
        ["be", 188],
        ["iq", 189],
        ["gm", 190],
        ["ma", 191],
        ["td", 192],
        ["kv", 193],
        ["lb", 194],
        ["sx", 195],
        ["dj", 196],
        ["er", 197],
        ["bi", 198],
        ["sn", 199],
        ["gn", 200],
        ["zw", 201],
        ["py", 202],
        ["by", 203],
        ["lv", 204],
        ["bt", 205],
        ["na", 206],
        ["bf", 207],
        ["ss", 208],
        ["cf", 209],
        ["md", 210],
        ["gz", 211],
        ["ke", 212],
        ["bw", 213],
        ["cz", 214],
        ["pr", 215],
        ["tn", 216],
        ["cu", 217],
        ["vn", 218],
        ["mg", 219],
        ["ve", 220],
        ["is", 221],
        ["np", 222],
        ["sr", 223],
        ["kg", 224],
    ],
    keylimitQty: {
        products2: {
            class: 1,
            group: 1,
            material: 1,
            color: 4,
            type: 1,
            special: 2,
        },
        parts2: {
            class: 1,
            group: 2,
            spec1: 2,
            spec2: 2,
            spec3: 2,
        },
    },
};

export default data;
